# 包含目录
applications_incdirs = include_directories(
  '.',
  'services/cmd',
  'services/valve',
  # 'services',
  # 'services/log',
  # 'tasks',
)

# 源文件
applications_sources = files(
  'main.c',
  'bsp.c',
  'services/valve/valve_counter.c',
  'services/valve/valve_handler.c',
  'services/valve/valve_conf.c',
  'services/cmd/cmd.c',
  'services/cmd/cmd_conf.c',
)