# 包含目录
log_incs = include_directories(
  'port',
  'modbus/rtu',
  'modbus/include',
)

# 源文件
log_srcs = files(
  './modbus/functions/mbfunccoils.c',
  './modbus/functions/mbfuncdiag.c',
  './modbus/functions/mbfuncdisc.c',
  './modbus/functions/mbfuncholding.c',
  './modbus/functions/mbfuncinput.c',
  './modbus/functions/mbfuncother.c',
  './modbus/functions/mbutils.c',
  './modbus/mb.c',
  './modbus/rtu/mbcrc.c',
  './modbus/rtu/mbrtu.c',
  './port/qpc/port.c',
  './port/qpc/portevent.c',
  './port/qpc/portserial.c',
  './port/qpc/porttimer.c',
  './port/user_mb_app.c',
  # './modbus/functions/mbfunccoils_m.c',
  # './modbus/functions/mbfuncdisc_m.c',
  # './modbus/functions/mbfuncholding_m.c',
  # './modbus/functions/mbfuncinput_m.c',
  # './modbus/mb_m.c',
  # './modbus/rtu/mbrtu_m.c',
  # './port/qpc/portevent_m.c',
  # './port/qpc/portserial_m.c',
  # './port/qpc/porttimer_m.c'
  # './port/user_mb_app_m.c',,
)