//$file${.::hello.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: hello.qm
// File:  ${.::hello.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::hello.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"    // QP/C real-time embedded framework
#include "bsp.h"    // Board Support Package interface
#include "stdio.h"
#include "hello.h"
#include "cmd.h"
#include "user_mb_app.h"

// ask QM to declare the Blinky class
//$declare${AOs::Hello} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Hello} ..............................................................
typedef struct Hello {
// protected:
    QActive super;

// private:
    QTimeEvt ledEvt;

// public:
    QTimeEvt modbusEvt;
} Hello;

extern Hello Hello_inst;

// protected:
static QState Hello_initial(Hello * const me, void const * const par);
static QState Hello_NORMAL(Hello * const me, QEvt const * const e);
static QState Hello_off(Hello * const me, QEvt const * const e);
static QState Hello_on(Hello * const me, QEvt const * const e);
//$enddecl${AOs::Hello} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Hello} ........................................................
QActive * const AO_Hello = &Hello_inst.super;

//${Shared::Hello_ctor} ......................................................
void Hello_ctor(void) {
    Hello * const me = &Hello_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Hello_initial));
    QTimeEvt_ctorX(&me->ledEvt, &me->super, BLINKY_SIG, 0U);
    QTimeEvt_ctorX(&me->modbusEvt, &me->super, MODBUS_POLL_SIG, 0U);
}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Hello} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Hello} ..............................................................
Hello Hello_inst;

//${AOs::Hello::SM} ..........................................................
static QState Hello_initial(Hello * const me, void const * const par) {
    //${AOs::Hello::SM::initial}
    (void)par; // unused parameter
    QTimeEvt_armX(&me->ledEvt, BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);
    QTimeEvt_armX(&me->modbusEvt, 1, 1);

    eMBInit(MB_RTU, 0x01, 1, 9600, MB_PAR_NONE);
    eMBEnable();

    cmd_init();

    QS_FUN_DICTIONARY(&Hello_NORMAL);
    QS_FUN_DICTIONARY(&Hello_off);
    QS_FUN_DICTIONARY(&Hello_on);

    return Q_TRAN(&Hello_off);
}

//${AOs::Hello::SM::NORMAL} ..................................................
static QState Hello_NORMAL(Hello * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Hello::SM::NORMAL::MODBUS_POLL}
        case MODBUS_POLL_SIG: {
            eMBPoll();
            extern USHORT usSRegHoldBuf[S_REG_HOLDING_NREGS];
            usSRegHoldBuf[3] = 0x1234;
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Hello::SM::NORMAL::USER_COMMAND}
        case USER_COMMAND_SIG: {
            CmdEvt const* const cmdEvt = (CmdEvt const*)e;
            cmd_execute(cmdEvt->msg);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Hello::SM::NORMAL::off} .............................................
static QState Hello_off(Hello * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Hello::SM::NORMAL::off}
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Hello::SM::NORMAL::off::BLINKY}
        case BLINKY_SIG: {
            status_ = Q_TRAN(&Hello_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&Hello_NORMAL);
            break;
        }
    }
    return status_;
}

//${AOs::Hello::SM::NORMAL::on} ..............................................
static QState Hello_on(Hello * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Hello::SM::NORMAL::on}
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Hello::SM::NORMAL::on::BLINKY}
        case BLINKY_SIG: {
            status_ = Q_TRAN(&Hello_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&Hello_NORMAL);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Hello} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
