//$file${.::valve_persist.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_persist.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_persist.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "valve.h"
#include "cmd.h"
#include "log.h"

#define PAGE_LEN 2048

static uint32_t        write_ptr;
static flash_fsm_t     flash_fsm;
static flash_request_t flash_request;

//$declare${AOs::ValvePersist} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValvePersist} .......................................................
typedef struct ValvePersist {
// protected:
    QMActive super;

// public:
    QTimeEvt processEvt;
    ValvePersistRequest request;
} ValvePersist;

extern ValvePersist ValvePersist_inst;

// protected:
static QState ValvePersist_initial(ValvePersist * const me, void const * const par);
static QState ValvePersist_Idle  (ValvePersist * const me, QEvt const * const e);
static QState ValvePersist_Idle_e(ValvePersist * const me);
static QState ValvePersist_Idle_x(ValvePersist * const me);
static QMState const ValvePersist_Idle_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValvePersist_Idle),
    Q_ACTION_CAST(&ValvePersist_Idle_e),
    Q_ACTION_CAST(&ValvePersist_Idle_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState ValvePersist_Complete  (ValvePersist * const me, QEvt const * const e);
static QState ValvePersist_Complete_e(ValvePersist * const me);
static QMState const ValvePersist_Complete_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValvePersist_Complete),
    Q_ACTION_CAST(&ValvePersist_Complete_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState ValvePersist_Prepare  (ValvePersist * const me, QEvt const * const e);
static QState ValvePersist_Prepare_e(ValvePersist * const me);
static QMState const ValvePersist_Prepare_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValvePersist_Prepare),
    Q_ACTION_CAST(&ValvePersist_Prepare_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState ValvePersist_Handle  (ValvePersist * const me, QEvt const * const e);
static QState ValvePersist_Handle_e(ValvePersist * const me);
static QMState const ValvePersist_Handle_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValvePersist_Handle),
    Q_ACTION_CAST(&ValvePersist_Handle_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::ValvePersist} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValvePersist} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValvePersist} ....................................................
QActive * const AO_ValvePersist = (QActive* const)&ValvePersist_inst.super;
//$enddef${AOs::AO_ValvePersist} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValvePersist_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValvePersist_ctor} ..................................................
void ValvePersist_ctor(void) {
    ValvePersist * const me = &ValvePersist_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&ValvePersist_initial));
    QTimeEvt_ctorX(&me->processEvt, (QActive*)me, VALVE_PERSIST_PROCESS_SIG, 0U);
}
//$enddef${AOs::ValvePersist_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValvePersist} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValvePersist} .......................................................
ValvePersist ValvePersist_inst;

//${AOs::ValvePersist::SM} ...................................................
static QState ValvePersist_initial(ValvePersist * const me, void const * const par) {
    //${AOs::ValvePersist::SM::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ValvePersist_Idle_s, // target state
        {
            Q_ACTION_CAST(&ValvePersist_Idle_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ValvePersist::SM::Idle} .............................................
//${AOs::ValvePersist::SM::Idle}
static QState ValvePersist_Idle_e(ValvePersist * const me) {
    Sleep_release(PERSIST_BIT);
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&ValvePersist_Idle_s);
}
//${AOs::ValvePersist::SM::Idle}
static QState ValvePersist_Idle_x(ValvePersist * const me) {
    Sleep_request(PERSIST_BIT);
    (void)me; // unused parameter
    return QM_EXIT(&ValvePersist_Idle_s);
}
//${AOs::ValvePersist::SM::Idle}
static QState ValvePersist_Idle(ValvePersist * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValvePersist::SM::Idle::VALVE_PERSIST_START}
        case VALVE_PERSIST_START_SIG: {
            ValveEvt const* ve = (ValveEvt const*)e;
            if (ve->evtType == VALVE_VALUE) {
                memcpy(&me->request, ve->msg, sizeof(ValvePersistRequest));
                write_ptr = me->request.write_ptr;
                QTimeEvt_armX(&me->processEvt, MS_TO_TICK(1), MS_TO_TICK(1));
            }
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &ValvePersist_Prepare_s, // target state
                {
                    Q_ACTION_CAST(&ValvePersist_Idle_x), // exit
                    Q_ACTION_CAST(&ValvePersist_Prepare_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ValvePersist::SM::Complete} .........................................
//${AOs::ValvePersist::SM::Complete}
static QState ValvePersist_Complete_e(ValvePersist * const me) {
    me->request.word_len--;
    me->request.data_ptr  += 4;
    me->request.write_ptr += 4;
    return QM_ENTRY(&ValvePersist_Complete_s);
}
//${AOs::ValvePersist::SM::Complete}
static QState ValvePersist_Complete(ValvePersist * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValvePersist::SM::Complete::VALVE_PERSIST_PROCESS}
        case VALVE_PERSIST_PROCESS_SIG: {
            //${AOs::ValvePersist::SM::Complete::VALVE_PERSIST_PR~::[remain==0]}
            if (me->request.word_len == 0) {
                QTimeEvt_disarm(&me->processEvt);
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValvePersist_Idle_s, // target state
                    {
                        Q_ACTION_CAST(&ValvePersist_Idle_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::ValvePersist::SM::Complete::VALVE_PERSIST_PR~::[remain>0]}
            else if (me->request.word_len > 0) {
                //${AOs::ValvePersist::SM::Complete::VALVE_PERSIST_PR~::[remain>0]::[neederase]}
                if (me->request.write_ptr - write_ptr == PAGE_LEN) {
                    write_ptr += PAGE_LEN;
                    static struct {
                        QMState const *target;
                        QActionHandler act[2];
                    } const tatbl_ = { // tran-action table
                        &ValvePersist_Prepare_s, // target state
                        {
                            Q_ACTION_CAST(&ValvePersist_Prepare_e), // entry
                            Q_ACTION_NULL // zero terminator
                        }
                    };
                    status_ = QM_TRAN(&tatbl_);
                }
                //${AOs::ValvePersist::SM::Complete::VALVE_PERSIST_PR~::[remain>0]::[directlywrite]}
                else if (me->request.write_ptr - write_ptr < PAGE_LEN) {
                    static struct {
                        QMState const *target;
                        QActionHandler act[2];
                    } const tatbl_ = { // tran-action table
                        &ValvePersist_Handle_s, // target state
                        {
                            Q_ACTION_CAST(&ValvePersist_Handle_e), // entry
                            Q_ACTION_NULL // zero terminator
                        }
                    };
                    status_ = QM_TRAN(&tatbl_);
                }
                else {
                    status_ = QM_UNHANDLED();
                }
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::ValvePersist::SM::Prepare} ..........................................
//${AOs::ValvePersist::SM::Prepare}
static QState ValvePersist_Prepare_e(ValvePersist * const me) {
    flash_fsm_init(&flash_fsm);
    flash_request.type    = FLASH_OP_ERASE_PAGE;
    flash_request.address = write_ptr;
    flash_request.data    = 0;
    flash_fsm_start(&flash_fsm, &flash_request, NULL, NULL);
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&ValvePersist_Prepare_s);
}
//${AOs::ValvePersist::SM::Prepare}
static QState ValvePersist_Prepare(ValvePersist * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValvePersist::SM::Prepare::VALVE_PERSIST_PROCESS}
        case VALVE_PERSIST_PROCESS_SIG: {
            flash_fsm_process(&flash_fsm);
            //${AOs::ValvePersist::SM::Prepare::VALVE_PERSIST_PR~::[success]}
            if (flash_fsm_get_result(&flash_fsm) == FLASH_RESULT_SUCCESS) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValvePersist_Handle_s, // target state
                    {
                        Q_ACTION_CAST(&ValvePersist_Handle_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::ValvePersist::SM::Prepare::VALVE_PERSIST_PR~::[fail]}
            else if ((flash_fsm_get_result(&flash_fsm) != FLASH_RESULT_SUCCESS) && (flash_fsm_get_result(&flash_fsm) != FLASH_RESULT_PENDING)) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValvePersist_Idle_s, // target state
                    {
                        Q_ACTION_CAST(&ValvePersist_Idle_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ValvePersist::SM::Handle} ...........................................
//${AOs::ValvePersist::SM::Handle}
static QState ValvePersist_Handle_e(ValvePersist * const me) {
    flash_fsm_init(&flash_fsm);
    flash_request.type    = FLASH_OP_PROGRAM_WORD;
    flash_request.address = me->request.write_ptr;
    flash_request.data    = *(uint32_t*)me->request.data_ptr;
    flash_fsm_start(&flash_fsm, &flash_request, NULL, NULL);
    return QM_ENTRY(&ValvePersist_Handle_s);
}
//${AOs::ValvePersist::SM::Handle}
static QState ValvePersist_Handle(ValvePersist * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValvePersist::SM::Handle::VALVE_PERSIST_PROCESS}
        case VALVE_PERSIST_PROCESS_SIG: {
            flash_fsm_process(&flash_fsm);
            //${AOs::ValvePersist::SM::Handle::VALVE_PERSIST_PR~::[success]}
            if (flash_fsm_get_result(&flash_fsm) == FLASH_RESULT_SUCCESS) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValvePersist_Complete_s, // target state
                    {
                        Q_ACTION_CAST(&ValvePersist_Complete_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::ValvePersist::SM::Handle::VALVE_PERSIST_PR~::[fail]}
            else if ((flash_fsm_get_result(&flash_fsm) != FLASH_RESULT_SUCCESS) && (flash_fsm_get_result(&flash_fsm) != FLASH_RESULT_PENDING)) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValvePersist_Idle_s, // target state
                    {
                        Q_ACTION_CAST(&ValvePersist_Idle_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValvePersist} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
