//$file${.::valve_shower.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_shower.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_shower.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "valve.h"

//$declare${AOs::ValveShower} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveShower} ........................................................
typedef struct ValveShower {
// protected:
    QActive super;

// public:
} ValveShower;

extern ValveShower ValveShower_inst;

// protected:
static QState ValveShower_initial(ValveShower * const me, void const * const par);
static QState ValveShower_Wait(ValveShower * const me, QEvt const * const e);
static QState ValveShower_Handle(ValveShower * const me, QEvt const * const e);
//$enddecl${AOs::ValveShower} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveShower} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveShower} .....................................................
QActive * const AO_ValveShower = &ValveShower_inst.super;
//$enddef${AOs::AO_ValveShower} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveShower_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveShower_ctor} ...................................................
void ValveShower_ctor(void) {
    ValveShower * const me = &ValveShower_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&ValveShower_initial));
}
//$enddef${AOs::ValveShower_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveShower} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveShower} ........................................................
ValveShower ValveShower_inst;

//${AOs::ValveShower::SM} ....................................................
static QState ValveShower_initial(ValveShower * const me, void const * const par) {
    //${AOs::ValveShower::SM::initial}
    QActive_subscribe(&me->super, LOCK_ON_SIG);
    QActive_subscribe(&me->super, LOCK_OFF_SIG);
    QActive_subscribe(&me->super, VALVE_UPDATE_SIG);
    return Q_TRAN(&ValveShower_Wait);
}

//${AOs::ValveShower::SM::Wait} ..............................................
static QState ValveShower_Wait(ValveShower * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveShower::SM::Wait}
        case Q_ENTRY_SIG: {
            Sleep_request(SHOWER_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveShower::SM::Wait}
        case Q_EXIT_SIG: {
            Sleep_release(SHOWER_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveShower::SM::Wait::LOCK_OFF}
        case LOCK_OFF_SIG: {
            status_ = Q_TRAN(&ValveShower_Handle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::ValveShower::SM::Handle} ............................................
static QState ValveShower_Handle(ValveShower * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveShower::SM::Handle::LOCK_ON}
        case LOCK_ON_SIG: {
            status_ = Q_TRAN(&ValveShower_Wait);
            break;
        }
        //${AOs::ValveShower::SM::Handle::VALVE_UPDATE}
        case VALVE_UPDATE_SIG: {
            ValveEvt const *ve = (ValveEvt const *)e;
            printf("Position: %d/6 (%.1f°), Rotations: %d, Total Ticks: %d\r\n",
                   ve->value->position,
                   (ve->value->position * 360.0f / TICKS_PER_ROTATION),
                   ve->value->rotations,
                   ve->value->total_ticks);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveShower} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
