//$file${.::valve_handler.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_handler.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_handler.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "valve.h"
#include "cmd.h"
#include "user_mb_app.h"
#include "spi_flash.h"

#define CONFIG_FLASH_ADDRESS 0x0

cmd_config_t global_config = {
    .valve_count = 2,              // 默认阀门数量
    .dir         = 1,              // 默认方向
    .model       = "default_model" // 默认模型名称
};

//$declare${AOs::ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler} .......................................................
typedef struct ValveHandler {
// protected:
    QActive super;

// public:
    QTimeEvt timeEvt;
    QTimeEvt exitEvt;
} ValveHandler;

extern ValveHandler ValveHandler_inst;

// protected:
static QState ValveHandler_initial(ValveHandler * const me, void const * const par);
static QState ValveHandler_Idle(ValveHandler * const me, QEvt const * const e);
static QState ValveHandler_Handle(ValveHandler * const me, QEvt const * const e);
//$enddecl${AOs::ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveHandler} ....................................................
QActive * const AO_ValveHandler = &ValveHandler_inst.super;
//$enddef${AOs::AO_ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveHandler_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler_ctor} ..................................................
void ValveHandler_ctor(void) {
    ValveHandler * const me = &ValveHandler_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&ValveHandler_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->exitEvt, &me->super, VALVE_EXIT_SIG, 0U);
}
//$enddef${AOs::ValveHandler_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler} .......................................................
ValveHandler ValveHandler_inst;

//${AOs::ValveHandler::SM} ...................................................
static QState ValveHandler_initial(ValveHandler * const me, void const * const par) {
    //${AOs::ValveHandler::SM::initial}
    QActive_subscribe(&me->super, LOCK_ON_SIG);
    QActive_subscribe(&me->super, LOCK_OFF_SIG);
    QActive_subscribe(&me->super, VALVE_UPDATE_SIG);
    QActive_subscribe(&me->super, VALVE_CONFIG_WRITE_SIG);
    QActive_subscribe(&me->super, VALVE_CONFIG_READ_SIG);
    return Q_TRAN(&ValveHandler_Idle);
}

//${AOs::ValveHandler::SM::Idle} .............................................
static QState ValveHandler_Idle(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle}
        case Q_ENTRY_SIG: {
            #ifdef USE_MODBUS
            eMBInit(MB_RTU, 0x01, 1, 9600, MB_PAR_NONE);
            eMBEnable();
            QTimeEvt_armX(&me->timeEvt, 1, 1);
            #endif
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::LOCK_OFF}
        case LOCK_OFF_SIG: {
            status_ = Q_TRAN(&ValveHandler_Handle);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::VALVE_DAILY}
        case VALVE_DAILY_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::TIMEOUT}
        case TIMEOUT_SIG: {
            #ifdef USE_MODBUS
            eMBPoll();
            #endif
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::ValveHandler::SM::Idle::Handle} .....................................
static QState ValveHandler_Handle(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle::Handle}
        case Q_ENTRY_SIG: {
            Sleep_release(HANDLER_BIT);
            sFLASH_Init();
            cmd_config_t _read_config = {0};
            sFLASH_ReadBuffer((uint8_t*)&_read_config, CONFIG_FLASH_ADDRESS, sizeof(cmd_config_t));
            bool all_ff = true;
            for (size_t i = 0; i < sizeof(cmd_config_t); ++i) {
                if (((uint8_t*)&_read_config)[i] != 0xFF) {
                    all_ff = false;
                    break;
                }
            }
            if (!all_ff) {
                // 数据合法，复制到全局变量_config
                global_config = _read_config;
                printf("Config read from flash and applied.\r\n");
                } else {
                printf("Flash config is empty (all FF), using default config.\r\n");
            }
            status_ = Q_HANDLED();
            break;
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::LOCK_ON}
        case LOCK_ON_SIG: {
            QTimeEvt_armX(&me->exitEvt, 500, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_UPDATE}
        case VALVE_UPDATE_SIG: {
            ValveEvt const *ve = (ValveEvt const *)e;
            ValveVal const *val = (ValveVal const *)ve->msg;
            printf("Position: %d/6, Rotations: %d, Total Ticks: %d\r\n",
                val->position,
                val->total_ticks / TICKS_PER_ROTATION,
                val->total_ticks);
            if (val->total_ticks > global_config.valve_count * 6) {
                lcd_set_char(LCD_CHAR_OPEN_CHINESE, true);
                lcd_set_char(LCD_CHAR_OPEN_ARROW, true);
                lcd_set_char(LCD_CHAR_CLOSE_CHINESE, false);
                lcd_set_char(LCD_CHAR_CLOSE_ARROW, false);
            } else if (val->total_ticks <= 0) {
                lcd_set_char(LCD_CHAR_CLOSE_CHINESE, true);
                lcd_set_char(LCD_CHAR_CLOSE_ARROW, true);
                lcd_set_char(LCD_CHAR_OPEN_CHINESE, false);
                lcd_set_char(LCD_CHAR_OPEN_ARROW, false);
            }
            #ifdef USE_MODBUS
            QF_CRIT_ENTRY();
            extern USHORT usSRegHoldBuf[S_REG_HOLDING_NREGS];
            usSRegHoldBuf[1] = val->total_ticks > 0 ? 1 : 2;
            usSRegHoldBuf[2] = val->total_ticks / TICKS_PER_ROTATION;
            usSRegHoldBuf[3] = val->total_ticks > global_config.valve_count * 6 ? 1 : 2;
            QF_CRIT_EXIT();
            #endif
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_CONFIG_WRITE}
        case VALVE_CONFIG_WRITE_SIG: {
            ValveEvt const *ve = (ValveEvt const *)e;
            cmd_config_t const *config = (cmd_config_t const *)ve->msg;
            // 擦除扇区
            sFLASH_EraseSector(CONFIG_FLASH_ADDRESS);
            // 写入配置数据
            sFLASH_WriteBuffer((uint8_t*)config, CONFIG_FLASH_ADDRESS, sizeof(cmd_config_t));
            printf("Config written to flash.\r\n");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_CONFIG_READ}
        case VALVE_CONFIG_READ_SIG: {
            ValveEvt const*     ve     = (ValveEvt const*)e;
            cmd_config_t const* config = (cmd_config_t const*)ve->msg;
            sFLASH_ReadBuffer((uint8_t*)config, CONFIG_FLASH_ADDRESS, sizeof(cmd_config_t));
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_EXIT}
        case VALVE_EXIT_SIG: {
            //sFLASH_WriteBuffer
            printf("write flash");
            sFLASH_DeInit();
            Sleep_request(HANDLER_BIT);
            status_ = Q_TRAN(&ValveHandler_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&ValveHandler_Idle);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
