//$file${.::valve.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __VALVE_H__
#define __VALVE_H__

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AppSignals} ......................................................
enum_t AppSignals {
    LOCK_ON_SIG = Q_USER_SIG,
    LOCK_OFF_SIG,
    VALVE_UPDATE_SIG,
    MAX_PUB_SIG,

    TIMEOUT_SIG,
    MAX_SIG,
};

//${Shared::ValveEvt} ........................................................
typedef struct {
// protected:
    QEvt super;

// public:
    ValveVal* value;
} ValveEvt;

//${Shared::ValveVal} ........................................................
typedef struct {
// public:
    int32_t total_ticks;
    int32_t rotations;
    int32_t position;
} ValveVal;

//${Shared::Sleep_bits} ......................................................
extern uint32_t Sleep_bits;

//${Shared::Sleep_bit_slot} ..................................................
enum_t Sleep_bit_slot {
    COUNTER_BIT = 1 << 0,
    SHOER_BIT   = 1 << 1,
};

//${Shared::Sleep_request} ...................................................
static inline void Sleep_request(uint32_t bit) {
    Sleep_bits |= bit;
}

//${Shared::Sleep_release} ...................................................
static inline void Sleep_release(uint32_t bit) {
    Sleep_bits &= ~bit;
}
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // __VALVE_H__
