//$file${.::valve_handler.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_handler.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_handler.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "valve.h"
#include "cmd.h"
#include "user_mb_app.h"

//$declare${AOs::ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler} .......................................................
typedef struct ValveHandler {
// protected:
    QActive super;

// public:
    QTimeEvt timeEvt;
} ValveHandler;

extern ValveHandler ValveHandler_inst;

// protected:
static QState ValveHandler_initial(ValveHandler * const me, void const * const par);
static QState ValveHandler_Idle(ValveHandler * const me, QEvt const * const e);
static QState ValveHandler_Handle(ValveHandler * const me, QEvt const * const e);
//$enddecl${AOs::ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveHandler} ....................................................
QActive * const AO_ValveHandler = &ValveHandler_inst.super;
//$enddef${AOs::AO_ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveHandler_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler_ctor} ..................................................
void ValveHandler_ctor(void) {
    ValveHandler * const me = &ValveHandler_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&ValveHandler_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${AOs::ValveHandler_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler} .......................................................
ValveHandler ValveHandler_inst;

//${AOs::ValveHandler::SM} ...................................................
static QState ValveHandler_initial(ValveHandler * const me, void const * const par) {
    //${AOs::ValveHandler::SM::initial}
    QActive_subscribe(&me->super, LOCK_ON_SIG);
    QActive_subscribe(&me->super, LOCK_OFF_SIG);
    QActive_subscribe(&me->super, VALVE_UPDATE_SIG);
    QActive_subscribe(&me->super, VALVE_CONFIG_WRITE_SIG);
    QActive_subscribe(&me->super, VALVE_CONFIG_READ_SIG);
    return Q_TRAN(&ValveHandler_Idle);
}

//${AOs::ValveHandler::SM::Idle} .............................................
static QState ValveHandler_Idle(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle}
        case Q_ENTRY_SIG: {
            #ifdef USE_MODBUS
            eMBInit(MB_RTU, 0x01, 1, 115200,  MB_PAR_EVEN);
            eMBEnable();
            QTimeEvt_armX(&me->timeEvt, 1, 1);
            #endif
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::LOCK_OFF}
        case LOCK_OFF_SIG: {
            status_ = Q_TRAN(&ValveHandler_Handle);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::VALVE_DAILY}
        case VALVE_DAILY_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::TIMEOUT}
        case TIMEOUT_SIG: {
            #ifdef USE_MODBUS
            eMBPoll();
            #endif
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::ValveHandler::SM::Idle::Handle} .....................................
static QState ValveHandler_Handle(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle::Handle}
        case Q_ENTRY_SIG: {
            Sleep_release(HANDLER_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle}
        case Q_EXIT_SIG: {
            Sleep_request(HANDLER_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::LOCK_ON}
        case LOCK_ON_SIG: {
            status_ = Q_TRAN(&ValveHandler_Idle);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_UPDATE}
        case VALVE_UPDATE_SIG: {
            ValveEvt const *ve = (ValveEvt const *)e;
            ValveVal const *val = (ValveVal const *)ve->msg;
            printf("Position: %d/6 (%.1f°), Rotations: %d, Total Ticks: %d\r\n",
                val->position,
                (val->position * 360.0f / TICKS_PER_ROTATION),
                val->rotations,
                val->total_ticks);
            #ifdef USE_MODBUS
            //TODO: update modbus reg for valve count
            #endif
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_CONFIG_WRITE}
        case VALVE_CONFIG_WRITE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_CONFIG_READ}
        case VALVE_CONFIG_READ_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&ValveHandler_Idle);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
