//$file${.::valve_conf.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_conf.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_conf.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "valve.h"

//$declare${AOs::ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf} ..........................................................
typedef struct ValveConf {
// protected:
    QActive super;

// public:
    QTimeEvt timeEvt;
} ValveConf;

extern ValveConf ValveConf_inst;

// protected:
static QState ValveConf_initial(ValveConf * const me, void const * const par);
static QState ValveConf_Active(ValveConf * const me, QEvt const * const e);
static QState ValveConf_Wait(ValveConf * const me, QEvt const * const e);
//$enddecl${AOs::ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveConf} .......................................................
QActive * const AO_ValveConf = &ValveConf_inst.super;
//$enddef${AOs::AO_ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveConf_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf_ctor} .....................................................
void ValveConf_ctor(void) {
    ValveConf * const me = &ValveConf_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&ValveConf_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${AOs::ValveConf_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf} ..........................................................
ValveConf ValveConf_inst;

//${AOs::ValveConf::SM} ......................................................
static QState ValveConf_initial(ValveConf * const me, void const * const par) {
    //${AOs::ValveConf::SM::initial}
    QActive_subscribe(&me->super, LOCK_ON_SIG);
    QActive_subscribe(&me->super, LOCK_OFF_SIG);
    QActive_subscribe(&me->super, VALVE_CONFIG_PARSE_SIG);
    return Q_TRAN(&ValveConf_Wait);
}

//${AOs::ValveConf::SM::Active} ..............................................
static QState ValveConf_Active(ValveConf * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveConf::SM::Active::TIMEOUT}
        case TIMEOUT_SIG: {
            static int count = 10;
            //blinky, toggle led
            count--;
            if(!count){
                QTimeEvt_disarm(&me->timeEvt);
                count = 0;
            }
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveConf::SM::Active::LOCK_ON}
        case LOCK_ON_SIG: {
            status_ = Q_TRAN(&ValveConf_Wait);
            break;
        }
        //${AOs::ValveConf::SM::Active::VALVE_CONFIG_PARSE}
        case VALVE_CONFIG_PARSE_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::ValveConf::SM::Wait} ................................................
static QState ValveConf_Wait(ValveConf * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveConf::SM::Wait}
        case Q_ENTRY_SIG: {
            Sleep_request(CONFIG_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveConf::SM::Wait}
        case Q_EXIT_SIG: {
            Sleep_release(CONFIG_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveConf::SM::Wait::LOCK_OFF}
        case LOCK_OFF_SIG: {
            status_ = Q_TRAN(&ValveConf_Active);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
