//$file${.::valve_counter.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_counter.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_counter.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "board.h"
#include "hall.h"
#include "valve.h"

//$declare${AOs::ValveCounter} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveCounter} .......................................................
typedef struct {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;
} ValveCounter;

// protected:
static QState ValveCounter_initial(ValveCounter * const me, void const * const par);
static QState ValveCounter_Wait(ValveCounter * const me, QEvt const * const e);
static QState ValveCounter_Work(ValveCounter * const me, QEvt const * const e);
//$enddecl${AOs::ValveCounter} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveCounter} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveCounter} .......................................................

//${AOs::ValveCounter::SM} ...................................................
static QState ValveCounter_initial(ValveCounter * const me, void const * const par) {
    //${AOs::ValveCounter::SM::initial}
    QActive_subscribe(&me->super, LOCK_ON_SIG);
    QActive_subscribe(&me->super, LOCK_OFF_SIG);
    return Q_TRAN(&ValveCounter_Wait);
}

//${AOs::ValveCounter::SM::Wait} .............................................
static QState ValveCounter_Wait(ValveCounter * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveCounter::SM::Wait}
        case Q_ENTRY_SIG: {
            sleep_request(COUNTER_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveCounter::SM::Wait}
        case Q_EXIT_SIG: {
            sleep_release(COUNTER_BIT);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveCounter::SM::Wait::LOCK_OFF}
        case LOCK_OFF_SIG: {
            status_ = Q_TRAN(&ValveCounter_Work);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::ValveCounter::SM::Work} .............................................
static QState ValveCounter_Work(ValveCounter * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveCounter::SM::Work}
        case Q_ENTRY_SIG: {
            hall_set_ctr(ENABLE);
            QTimeEvt_armX(&me->timeEvt, 1, 1);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveCounter::SM::Work}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            hall_set_ctr(DISABLE);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::ValveCounter::SM::Work::LOCK_ON}
        case LOCK_ON_SIG: {
            status_ = Q_TRAN(&ValveCounter_Wait);
            break;
        }
        //${AOs::ValveCounter::SM::Work::TIMEOUT}
        case TIMEOUT_SIG: {
            static uint8_t last_state = 0;
            static ValveVal _val = {0};
            uint8_t        new_state  = read_sensor_state();

            if (new_state != last_state && is_valid_state(&new_state)) {
                // 检查方向并更新旋转计数
                if (is_valid_state(&last_state)) {
                    int8_t dir = check_direction(&last_state, &new_state);
                    if (dir != 0) {
                        _val.total_ticks += dir;

                        // 更新位置计数
                        _val.position = (_val.total_ticks % TICKS_PER_ROTATION + TICKS_PER_ROTATION) % TICKS_PER_ROTATION;
                        // 更新圈数
                        _val.rotations = _val.total_ticks / TICKS_PER_ROTATION;
                        ValveEvt *pe = Q_NEW(ValveEvt, VALVE_UPDATE_SIG);
                        QACTIVE_PUBLISH(&pe->super, &me->super);
                    } else {
                        // 处理错误（如复位状态）
                    }
                }
                last_state = new_state;
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveCounter} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
