//$file${.::valve_transfer.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_transfer.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_transfer.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "at_lora.h"
#include "valve.h"
#include "log.h"

static at_process_result_t result;

//$declare${AOs::ValveTransfer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveTransfer} ......................................................
typedef struct ValveTransfer {
// protected:
    QMActive super;

// public:
    QTimeEvt timeEvt;
    uint32_t tick;
    bool isActive;
} ValveTransfer;

extern ValveTransfer ValveTransfer_inst;

// protected:
static QState ValveTransfer_initial(ValveTransfer * const me, void const * const par);
static QState ValveTransfer_Idle  (ValveTransfer * const me, QEvt const * const e);
static QState ValveTransfer_Idle_e(ValveTransfer * const me);
static QMState const ValveTransfer_Idle_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValveTransfer_Idle),
    Q_ACTION_CAST(&ValveTransfer_Idle_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState ValveTransfer_Prepare  (ValveTransfer * const me, QEvt const * const e);
static QState ValveTransfer_Prepare_e(ValveTransfer * const me);
static QMState const ValveTransfer_Prepare_s = {
    &ValveTransfer_Idle_s, // superstate
    Q_STATE_CAST(&ValveTransfer_Prepare),
    Q_ACTION_CAST(&ValveTransfer_Prepare_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState ValveTransfer_Transfer  (ValveTransfer * const me, QEvt const * const e);
static QState ValveTransfer_Transfer_e(ValveTransfer * const me);
static QMState const ValveTransfer_Transfer_s = {
    &ValveTransfer_Idle_s, // superstate
    Q_STATE_CAST(&ValveTransfer_Transfer),
    Q_ACTION_CAST(&ValveTransfer_Transfer_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::ValveTransfer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveTransfer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveTransfer} ...................................................
QActive * const AO_ValveTransfer = (QActive* const)&ValveTransfer_inst.super;
//$enddef${AOs::AO_ValveTransfer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveTransfer_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveTransfer_ctor} .................................................
void ValveTransfer_ctor(void) {
    ValveTransfer * const me = &ValveTransfer_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&ValveTransfer_initial));
    QTimeEvt_ctorX(&me->timeEvt, (QActive*)me, TIMEOUT_SIG, 0U);
}
//$enddef${AOs::ValveTransfer_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveTransfer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveTransfer} ......................................................
ValveTransfer ValveTransfer_inst;

//${AOs::ValveTransfer::SM} ..................................................
static QState ValveTransfer_initial(ValveTransfer * const me, void const * const par) {
    //${AOs::ValveTransfer::SM::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ValveTransfer_Idle_s, // target state
        {
            Q_ACTION_CAST(&ValveTransfer_Idle_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ValveTransfer::SM::Idle} ............................................
//${AOs::ValveTransfer::SM::Idle}
static QState ValveTransfer_Idle_e(ValveTransfer * const me) {
    APP_LOG_INFO("lorawan off");
    QTimeEvt_disarm(&me->timeEvt);
    Sleep_release(TRANSFER_BIT);
    me->isActive = false;
    return QM_ENTRY(&ValveTransfer_Idle_s);
}
//${AOs::ValveTransfer::SM::Idle}
static QState ValveTransfer_Idle(ValveTransfer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveTransfer::SM::Idle::VALVE_TRANSFER}
        case VALVE_TRANSFER_SIG: {
            if (!me->isActive) {
                at_lorawan_init();
                QTimeEvt_armX(&me->timeEvt, MS_TO_TICK(1), MS_TO_TICK(1));
                Sleep_request(TRANSFER_BIT);
                me->isActive = true;
            }
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveTransfer::SM::Idle::TIMEOUT}
        case TIMEOUT_SIG: {
            //${AOs::ValveTransfer::SM::Idle::TIMEOUT::[is_ready]}
            if (at_lorawan_is_ready() == true) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValveTransfer_Prepare_s, // target state
                    {
                        Q_ACTION_CAST(&ValveTransfer_Prepare_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ValveTransfer::SM::Idle::Prepare} ...................................
//${AOs::ValveTransfer::SM::Idle::Prepare}
static QState ValveTransfer_Prepare_e(ValveTransfer * const me) {
    me->tick = 0;
    at_lorawan_config_prepare();
    return QM_ENTRY(&ValveTransfer_Prepare_s);
}
//${AOs::ValveTransfer::SM::Idle::Prepare}
static QState ValveTransfer_Prepare(ValveTransfer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveTransfer::SM::Idle::Prepare::TIMEOUT}
        case TIMEOUT_SIG: {
            result = at_lorawan_poll(me->tick);
            //${AOs::ValveTransfer::SM::Idle::Prepare::TIMEOUT::[success]}
            if (result == AT_PROCESS_COMPLETE) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &ValveTransfer_Transfer_s, // target state
                    {
                        Q_ACTION_CAST(&ValveTransfer_Transfer_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::ValveTransfer::SM::Idle::Prepare::TIMEOUT::[fail]}
            else if (result == AT_PROCESS_ERROR) {
                static QMTranActTable const tatbl_ = { // tran-action table
                    &ValveTransfer_Idle_s, // target state
                    {
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ValveTransfer::SM::Idle::Transfer} ..................................
//${AOs::ValveTransfer::SM::Idle::Transfer}
static QState ValveTransfer_Transfer_e(ValveTransfer * const me) {
    me->tick = 0;
    at_lorawan_send_prepare("hello");
    return QM_ENTRY(&ValveTransfer_Transfer_s);
}
//${AOs::ValveTransfer::SM::Idle::Transfer}
static QState ValveTransfer_Transfer(ValveTransfer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveTransfer::SM::Idle::Transfer::TIMEOUT}
        case TIMEOUT_SIG: {
            result = at_lorawan_poll(me->tick);
            //${AOs::ValveTransfer::SM::Idle::Transfer::TIMEOUT::[fail]}
            if (result == AT_PROCESS_ERROR) {
                static QMTranActTable const tatbl_ = { // tran-action table
                    &ValveTransfer_Idle_s, // target state
                    {
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::ValveTransfer::SM::Idle::Transfer::TIMEOUT::[success]}
            else if (result == AT_PROCESS_COMPLETE) {
                static QMTranActTable const tatbl_ = { // tran-action table
                    &ValveTransfer_Idle_s, // target state
                    {
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveTransfer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
