//$file${.::valve_conf.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_conf.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_conf.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "cmd.h"
#include "valve.h"

//$declare${AOs::ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf} ..........................................................
typedef struct ValveConf {
// protected:
    QMActive super;

// public:
    QTimeEvt timeEvt;
} ValveConf;

extern ValveConf ValveConf_inst;

// protected:
static QState ValveConf_initial(ValveConf * const me, void const * const par);
static QState ValveConf_Active  (ValveConf * const me, QEvt const * const e);
static QState ValveConf_Active_e(ValveConf * const me);
static QState ValveConf_Active_x(ValveConf * const me);
static QMState const ValveConf_Active_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValveConf_Active),
    Q_ACTION_CAST(&ValveConf_Active_e),
    Q_ACTION_CAST(&ValveConf_Active_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState ValveConf_Wait  (ValveConf * const me, QEvt const * const e);
static QState ValveConf_Wait_e(ValveConf * const me);
static QState ValveConf_Wait_x(ValveConf * const me);
static QMState const ValveConf_Wait_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValveConf_Wait),
    Q_ACTION_CAST(&ValveConf_Wait_e),
    Q_ACTION_CAST(&ValveConf_Wait_x),
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveConf} .......................................................
QActive * const AO_ValveConf = (QActive* const)&ValveConf_inst.super;
//$enddef${AOs::AO_ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveConf_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf_ctor} .....................................................
void ValveConf_ctor(void) {
    ValveConf * const me = &ValveConf_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&ValveConf_initial));
    QTimeEvt_ctorX(&me->timeEvt, (QActive*)me, TIMEOUT_SIG, 0U);
}
//$enddef${AOs::ValveConf_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf} ..........................................................
ValveConf ValveConf_inst;

//${AOs::ValveConf::SM} ......................................................
static QState ValveConf_initial(ValveConf * const me, void const * const par) {
    //${AOs::ValveConf::SM::initial}
    QActive_subscribe((QActive*)me, LOCK_SIG);
    QActive_subscribe((QActive*)me, UNLOCK_SIG);
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ValveConf_Wait_s, // target state
        {
            Q_ACTION_CAST(&ValveConf_Wait_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ValveConf::SM::Active} ..............................................
//${AOs::ValveConf::SM::Active}
static QState ValveConf_Active_e(ValveConf * const me) {
    cmd_init();
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&ValveConf_Active_s);
}
//${AOs::ValveConf::SM::Active}
static QState ValveConf_Active_x(ValveConf * const me) {
    cmd_deinit();
    (void)me; // unused parameter
    return QM_EXIT(&ValveConf_Active_s);
}
//${AOs::ValveConf::SM::Active}
static QState ValveConf_Active(ValveConf * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveConf::SM::Active::TIMEOUT}
        case TIMEOUT_SIG: {
            static int count = 10;
            //blinky, toggle led
            count--;
            if(!count){
                QTimeEvt_disarm(&me->timeEvt);
                count = 0;
            }
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveConf::SM::Active::LOCK}
        case LOCK_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &ValveConf_Wait_s, // target state
                {
                    Q_ACTION_CAST(&ValveConf_Active_x), // exit
                    Q_ACTION_CAST(&ValveConf_Wait_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::ValveConf::SM::Active::VALVE_CMD_PARSE}
        case VALVE_CMD_PARSE_SIG: {
            ValveEvt* const evt = (ValveEvt*)e;
            if (evt->evtType == VALVE_CMD) {
                cmd_execute((char*)evt->msg);
            }
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::ValveConf::SM::Wait} ................................................
//${AOs::ValveConf::SM::Wait}
static QState ValveConf_Wait_e(ValveConf * const me) {
    Sleep_release(CONFIG_BIT);
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&ValveConf_Wait_s);
}
//${AOs::ValveConf::SM::Wait}
static QState ValveConf_Wait_x(ValveConf * const me) {
    Sleep_request(CONFIG_BIT);
    (void)me; // unused parameter
    return QM_EXIT(&ValveConf_Wait_s);
}
//${AOs::ValveConf::SM::Wait}
static QState ValveConf_Wait(ValveConf * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveConf::SM::Wait::UNLOCK}
        case UNLOCK_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &ValveConf_Active_s, // target state
                {
                    Q_ACTION_CAST(&ValveConf_Wait_x), // exit
                    Q_ACTION_CAST(&ValveConf_Active_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
