//$file${.::valve_counter.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_counter.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_counter.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "cmd.h"
#include "valve.h"

// ======================== 方向映射表 ========================
typedef struct {
    uint8_t from; // 起始状态
    uint8_t to;   // 目标状态
    int8_t  dir;  // 方向 (+1正转, -1反转)
} TransitionRule;

static ValveEvt evt;
static uint32_t new_state;
static uint32_t last_state;
#ifdef DEBUG
SEGGER_SYSVIEW_DATA_SAMPLE _hall_data;
SEGGER_SYSVIEW_DATA_SAMPLE _val_tick;
#endif

//$declare${AOs::ValveCounter} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveCounter} .......................................................
typedef struct ValveCounter {
// protected:
    QMActive super;

// private:
    QTimeEvt timeEvt;

// public:
} ValveCounter;

extern ValveCounter ValveCounter_inst;

// protected:
static QState ValveCounter_initial(ValveCounter * const me, void const * const par);
static QState ValveCounter_Wait  (ValveCounter * const me, QEvt const * const e);
static QMState const ValveCounter_Wait_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValveCounter_Wait),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState ValveCounter_Work  (ValveCounter * const me, QEvt const * const e);
static QState ValveCounter_Work_e(ValveCounter * const me);
static QState ValveCounter_Work_x(ValveCounter * const me);
static QMState const ValveCounter_Work_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValveCounter_Work),
    Q_ACTION_CAST(&ValveCounter_Work_e),
    Q_ACTION_CAST(&ValveCounter_Work_x),
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::ValveCounter} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// 方向映射表(64x64, 未定义部分置0)
static const int8_t rules[64][64] = {
    // 单触发+1
    [0x01][0x02] = 1,
    [0x02][0x04] = 1,
    [0x04][0x08] = 1,
    [0x08][0x10] = 1,
    [0x10][0x20] = 1,
    [0x20][0x01] = 1, // 环形连接
    // 单触发-1
    [0x02][0x01] = -1,
    [0x04][0x02] = -1,
    [0x08][0x04] = -1,
    [0x10][0x08] = -1,
    [0x20][0x10] = -1,
    [0x01][0x20] = -1, // 环形连接
    // 单触发+2
    [0x01][0x04] = 2,
    [0x02][0x08] = 2,
    [0x04][0x10] = 2,
    [0x08][0x20] = 2,
    [0x10][0x01] = 2,
    [0x20][0x02] = 2, // 环形连接
    // 单触发-2
    [0x04][0x01] = -2,
    [0x08][0x02] = -2,
    [0x10][0x04] = -2,
    [0x20][0x08] = -2,
    [0x01][0x10] = -2,
    [0x02][0x20] = -2, // 环形连接
    // 双触发+1(单-->双)
    [0x01][0x03] = 1,
    [0x02][0x06] = 1,
    [0x04][0x0C] = 1,
    [0x08][0x18] = 1,
    [0x10][0x30] = 1,
    [0x20][0x21] = 1, // 环形连接
    // 双触发-1(单-->双)
    [0x03][0x01] = -1,
    [0x06][0x02] = -1,
    [0x0C][0x04] = -1,
    [0x18][0x08] = -1,
    [0x30][0x10] = -1,
    [0x21][0x20] = -1, // 环形连接
    // 双触发+2(单-->双)
    [0x01][0x06] = 2,
    [0x02][0x0C] = 2,
    [0x04][0x18] = 2,
    [0x08][0x30] = 2,
    [0x10][0x21] = 2,
    [0x20][0x03] = 2, // 环形连接
    // 双触发-2(单-->双)
    [0x06][0x01] = -2,
    [0x0C][0x02] = -2,
    [0x18][0x04] = -2,
    [0x30][0x08] = -2,
    [0x21][0x10] = -2,
    [0x03][0x20] = -2, // 环形连接
    // 双触发+3(单-->双)
    [0x01][0x0C] = 3,
    [0x02][0x18] = 3,
    [0x04][0x30] = 3,
    [0x08][0x21] = 3,
    [0x10][0x03] = 3,
    [0x20][0x06] = 3, // 环形连接
    // 双触发-3(单-->双)
    [0x0C][0x01] = -3,
    [0x18][0x02] = -3,
    [0x30][0x04] = -3,
    [0x21][0x08] = -3,
    [0x03][0x10] = -3,
    [0x06][0x20] = -3, // 环形连接
};

// ======================== 核心逻辑 ========================
// 读取传感器状态（6-bit编码）
static inline uint8_t read_sensor_state(void)
{
    return ~(uint8_t)(GPIOC->PID & 0xf | ((GPIOA->PID & 0x6) << 3)) & 0x3f;
}

// 检查是否为合法状态（单或双传感器触发）
static bool is_valid_state(uint32_t* state)
{
    switch (*state) {
        // 单传感器触发
        case 0x01:
        case 0x02:
        case 0x04:
        case 0x08:
        case 0x10:
        case 0x20:
        // 双传感器触发（相邻两个）
        case 0x03:
        case 0x06:
        case 0x0C:
        case 0x18:
        case 0x30:
        case 0x21:
            return true;
        default:
            return false; // 非法状态（如三个传感器同时触发）,无传感器触发
    }
}

// 检查方向（允许1-bit误差）
static int8_t check_direction(uint32_t* old, uint32_t* new)
{
    return global_config.dir * rules[*old][*new]; // 直接访问映射表
}

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveCounter} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveCounter} ....................................................
QActive * const AO_ValveCounter = (QActive* const)&ValveCounter_inst.super;
//$enddef${AOs::AO_ValveCounter} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveCounter_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveCounter_ctor} ..................................................
void ValveCounter_ctor(void) {
    ValveCounter * const me = &ValveCounter_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&ValveCounter_initial));
    QTimeEvt_ctorX(&me->timeEvt, (QActive*)me, TIMEOUT_SIG, 0U);
}
//$enddef${AOs::ValveCounter_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveCounter} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveCounter} .......................................................
ValveCounter ValveCounter_inst;

//${AOs::ValveCounter::SM} ...................................................
static QState ValveCounter_initial(ValveCounter * const me, void const * const par) {
    //${AOs::ValveCounter::SM::initial}
    QActive_subscribe((QActive*)me, VALVE_LOCK_SIG);
    QActive_subscribe((QActive*)me, VALVE_UNLOCK_SIG);
    #ifdef DEBUG
    _hall_data.ID          = 0;
    _hall_data.pValue.pU32 = (U32*)&new_state;
    _val_tick.ID           = 1;
    _val_tick.pValue.pI32  = (I32*)&global_valve_value->total_ticks;
    #endif
    static QMTranActTable const tatbl_ = { // tran-action table
        &ValveCounter_Wait_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ValveCounter::SM::Wait} .............................................
//${AOs::ValveCounter::SM::Wait}
static QState ValveCounter_Wait(ValveCounter * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveCounter::SM::Wait::VALVE_UNLOCK}
        case VALVE_UNLOCK_SIG: {
            Sleep_request(COUNTER_BIT);
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &ValveCounter_Work_s, // target state
                {
                    Q_ACTION_CAST(&ValveCounter_Work_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ValveCounter::SM::Work} .............................................
//${AOs::ValveCounter::SM::Work}
static QState ValveCounter_Work_e(ValveCounter * const me) {
    hall_set_ctr(ENABLE);
    QTimeEvt_armX(&me->timeEvt, 1, 1);
    return QM_ENTRY(&ValveCounter_Work_s);
}
//${AOs::ValveCounter::SM::Work}
static QState ValveCounter_Work_x(ValveCounter * const me) {
    QTimeEvt_disarm(&me->timeEvt);
    hall_set_ctr(DISABLE);
    return QM_EXIT(&ValveCounter_Work_s);
}
//${AOs::ValveCounter::SM::Work}
static QState ValveCounter_Work(ValveCounter * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveCounter::SM::Work::VALVE_LOCK}
        case VALVE_LOCK_SIG: {
            Sleep_release(COUNTER_BIT);
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &ValveCounter_Wait_s, // target state
                {
                    Q_ACTION_CAST(&ValveCounter_Work_x), // exit
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::ValveCounter::SM::Work::TIMEOUT}
        case TIMEOUT_SIG: {
            new_state  = read_sensor_state();
            #ifdef DEBUG
            static bool first_load = true;
            if (new_state) {
                SEGGER_SYSVIEW_SampleData(&_hall_data);
            }
            if (first_load) {
                SEGGER_SYSVIEW_SampleData(&_val_tick);
                SEGGER_SYSVIEW_SampleData(&_hall_data);
            }
            #endif
            if (new_state != last_state && is_valid_state(&new_state)) {
                // 检查方向并更新旋转计数
                if (is_valid_state(&last_state)) {
                    global_valve_value->total_ticks += check_direction(&last_state, &new_state);
            #ifdef DEBUG
                    SEGGER_SYSVIEW_SampleData(&_val_tick);
                    first_load = false;
            #endif
                    QEvt_ctor(&evt.super, VALVE_UPDATE_SIG);
                    QACTIVE_PUBLISH(&evt.super, &me->super);
                    //QACTIVE_POST_X(AO_ValveHandler, &evt.super, 1, &me->super);
                }
                last_state = new_state;
            }

            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ValveCounter} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
