//$file${.::valve.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __VALVE_H__
#define __VALVE_H__

#include "cmd.h"

#ifdef DEBUG
#include "SEGGER_SYSVIEW.h"
#define VALVE_IDLE            0x400
#define VALVE_UPDATE          0x401
#define VALVE_PERSIST_START   0x402
#define VALVE_PERSIST_EARSE   0x403
#define VALVE_PERSIST_PROGRAM 0x404
#define VALVE_PERSIST_DONE    0x405
#endif

#define VALVE_STATUS_OFF  0
#define VALVE_STATUS_ON   1

#ifdef USE_MODBUS
#include "user_mb_app.h"
extern UCHAR ucSCoilBuf[S_COIL_NCOILS / 8];
#endif

#define TICKS_PER_ROTATION 6 // 每圈的跳变次数（6磁铁）

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AppSignals} ......................................................
enum AppSignals {
    VALVE_LOCK_SIG = Q_USER_SIG,
    VALVE_UNLOCK_SIG,
    VALVE_REBOOT_SIG,
    VALVE_DAILY_SIG,
    VALVE_UPDATE_SIG,
    VALVE_EXIT_SIG,
    VALVE_TRANSFER_SIG,
    VALVE_CMD_PARSE_SIG,
    VALVE_REFACTORY_SIG,
    VALVE_CONFIG_WRITE_SIG,
    VALVE_CONFIG_READ_SIG,
    VALVE_TUNING_START_SIG,
    VALVE_TUNING_STOP_SIG,
    VALVE_INFO_READ_SIG,
    VALVE_PERSIST_SIG,
    VALVE_PERSIST_START_SIG,
    VALVE_PERSIST_PROCESS_SIG,
    MAX_PUB_SIG,

    TIMEOUT_SIG,
    MAX_SIG,
};

//${Shared::Sleep_bits} ......................................................
extern volatile uint32_t Sleep_bits;

//${Shared::Sleep_slotbit} ...................................................
enum Sleep_slotbit {
    LOCK_BIT    = 1 << 0,
    COUNTER_BIT = 1 << 1,
    HANDLER_BIT = 1 << 2,
    CONFIG_BIT  = 1 << 3,
};

//${Shared::Sleep_request} ...................................................
static inline void Sleep_request(uint32_t bit) {
    Sleep_bits |= bit;
}

//${Shared::Sleep_release} ...................................................
static inline void Sleep_release(uint32_t bit) {
    Sleep_bits &= ~bit;
}

//${Shared::ValveVal} ........................................................
typedef struct {
// public:
    int32_t total_ticks;
    uint32_t current_status;
} ValveVal;

//${Shared::ValveEvtType} ....................................................
enum ValveEvtType {
    VALVE_VALUE,
    VALVE_CMD,
};

//${Shared::(*EvtHandle)(void*)} .............................................
typedef void  (*EvtHandle)(void*);

//${Shared::ValveEvt} ........................................................
typedef struct {
// protected:
    QEvt super;

// public:
    void * msg;
    EvtHandle handle;
    enum ValveEvtType evtType;
} ValveEvt;

//${Shared::ValveValStore} ...................................................
typedef struct {
// public:
    uint32_t flag;
    ValveVal val;
} ValveValStore;

//${Shared::ValvePersistRequest} .............................................
typedef struct {
// public:
    uint32_t word_len;
    uint32_t data_ptr;
    uint32_t write_ptr;
} ValvePersistRequest;
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::AO_ValveCounter} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveCounter} ....................................................
extern QActive * const AO_ValveCounter;
//$enddecl${AOs::AO_ValveCounter} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::ValveCounter_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveCounter_ctor} ..................................................
void ValveCounter_ctor(void);
//$enddecl${AOs::ValveCounter_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::AO_ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveHandler} ....................................................
extern QActive * const AO_ValveHandler;
//$enddecl${AOs::AO_ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::ValveHandler_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler_ctor} ..................................................
void ValveHandler_ctor(void);
//$enddecl${AOs::ValveHandler_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::AO_ValveConf} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveConf} .......................................................
extern QActive * const AO_ValveConf;
//$enddecl${AOs::AO_ValveConf} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::ValveConf_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveConf_ctor} .....................................................
void ValveConf_ctor(void);
//$enddecl${AOs::ValveConf_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::AO_ValvePersist} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValvePersist} ....................................................
extern QActive * const AO_ValvePersist;
//$enddecl${AOs::AO_ValvePersist} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::ValvePersist_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValvePersist_ctor} ..................................................
void ValvePersist_ctor(void);
//$enddecl${AOs::ValvePersist_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::AO_ValveTransfer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveTransfer} ...................................................
extern QActive * const AO_ValveTransfer;
//$enddecl${AOs::AO_ValveTransfer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::ValveTransfer_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveTransfer_ctor} .................................................
void ValveTransfer_ctor(void);
//$enddecl${AOs::ValveTransfer_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

extern ValveVal*    global_valve_value;
extern cmd_config_t global_config;

#endif // __VALVE_H__
