//$file${.::valve_handler.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: valve.qm
// File:  ${.::valve_handler.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::valve_handler.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "valve.h"
#include "cmd.h"
#include "spi_flash.h"
#include "log.h"
#ifdef USE_MODBUS
#include "user_mb_app.h"
#endif
#define CONF_ADDR_EXFLASH 0x0
#define DATA_ADDR_FLASH   0x0801F800

#define VALVE_STATUS_OFF  0
#define VALVE_STATUS_ON   1

ValveValStore global_valve_store = {
    .flag = FLAG_VAILD,
};
ValveVal*    global_valve_value = &global_valve_store.val;
cmd_config_t global_config      = {
         .flag  = FLAG_VAILD,
         .tick  = 12,             // 默认旋转阈值
         .dir   = -1,             // 默认方向，逆时针
         .model = "default_model" // 默认模型名称
};
static int32_t   last_total_ticks;
static bool      use_flash_data;
static QEvt      self_evt;
static EvtHandle update_handle;

//$declare${AOs::ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler} .......................................................
typedef struct ValveHandler {
// protected:
    QMActive super;

// public:
    QTimeEvt timeEvt;
    QTimeEvt exitEvt;
    QTimeEvt persistEvt;
} ValveHandler;

extern ValveHandler ValveHandler_inst;

// protected:
static QState ValveHandler_initial(ValveHandler * const me, void const * const par);
static QState ValveHandler_Idle  (ValveHandler * const me, QEvt const * const e);
static QState ValveHandler_Idle_e(ValveHandler * const me);
static QState ValveHandler_Idle_x(ValveHandler * const me);
static QMState const ValveHandler_Idle_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ValveHandler_Idle),
    Q_ACTION_CAST(&ValveHandler_Idle_e),
    Q_ACTION_CAST(&ValveHandler_Idle_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState ValveHandler_Handle  (ValveHandler * const me, QEvt const * const e);
static QMState const ValveHandler_Handle_s = {
    &ValveHandler_Idle_s, // superstate
    Q_STATE_CAST(&ValveHandler_Handle),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState ValveHandler_Tuning  (ValveHandler * const me, QEvt const * const e);
static QMState const ValveHandler_Tuning_s = {
    &ValveHandler_Handle_s, // superstate
    Q_STATE_CAST(&ValveHandler_Tuning),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::AO_ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::AO_ValveHandler} ....................................................
QActive * const AO_ValveHandler = (QActive* const)&ValveHandler_inst.super;
//$enddef${AOs::AO_ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveHandler_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler_ctor} ..................................................
void ValveHandler_ctor(void) {
    ValveHandler * const me = &ValveHandler_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&ValveHandler_initial));
    QTimeEvt_ctorX(&me->timeEvt, (QActive*)me, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->persistEvt, (QActive*)me, VALVE_PERSIST_SIG, 0U);
    QTimeEvt_ctorX(&me->exitEvt, (QActive*)me, VALVE_EXIT_SIG, 0U);
}
//$enddef${AOs::ValveHandler_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::ValveHandler} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ValveHandler} .......................................................
ValveHandler ValveHandler_inst;

//${AOs::ValveHandler::SM} ...................................................
static QState ValveHandler_initial(ValveHandler * const me, void const * const par) {
    //${AOs::ValveHandler::SM::initial}
    QActive_subscribe((QActive*)me, LOCK_SIG);
    QActive_subscribe((QActive*)me, UNLOCK_SIG);
    QActive_subscribe((QActive*)me, VALVE_UPDATE_SIG);
    QActive_subscribe((QActive*)me, VALVE_REBOOT_SIG);
    QActive_subscribe((QActive*)me, VALVE_REFACTORY_SIG);
    QActive_subscribe((QActive*)me, VALVE_CONFIG_WRITE_SIG);
    QActive_subscribe((QActive*)me, VALVE_CONFIG_READ_SIG);
    QActive_subscribe((QActive*)me, VALVE_TUNING_START_SIG);
    QActive_subscribe((QActive*)me, VALVE_TUNING_STOP_SIG);

    //get valve data from flash
    ValveValStore* _valve_store = (ValveValStore*)DATA_ADDR_FLASH;
    if (_valve_store->flag == FLAG_VAILD) {
        memcpy(&global_valve_store, (void*)DATA_ADDR_FLASH, sizeof(ValveValStore));
        APP_LOG_INFO("Load valve value from flash");
    }
    if (global_valve_value->current_status == VALVE_STATUS_ON) {
        lcd_set_char(LCD_CHAR_OPEN_CHINESE, true);
        lcd_set_char(LCD_CHAR_OPEN_ARROW, true);
        lcd_set_char(LCD_CHAR_CLOSE_CHINESE, false);
        lcd_set_char(LCD_CHAR_CLOSE_ARROW, false);
    } else {
        lcd_set_char(LCD_CHAR_CLOSE_CHINESE, true);
        lcd_set_char(LCD_CHAR_CLOSE_ARROW, true);
        lcd_set_char(LCD_CHAR_OPEN_CHINESE, false);
        lcd_set_char(LCD_CHAR_OPEN_ARROW, false);
    }

    //get valve config from spi flash
    sFLASH_Init();
    cmd_config_t _read_config = {0};
    sFLASH_ReadBuffer((uint8_t*)&_read_config, CONF_ADDR_EXFLASH, sizeof(cmd_config_t));
    if (_read_config.flag == FLAG_VAILD) {
        memcpy(&global_config, &_read_config, sizeof(cmd_config_t));
        APP_LOG_INFO("Config read from flash and applied");
    } else {
        APP_LOG_INFO("Flash config is invaild, using default config");
    }
    sFLASH_DeInit();
    #ifdef USE_MODBUS
    eMBInit(MB_RTU, 0x01, 1, 9600, MB_PAR_NONE);
    eMBEnable();
    QTimeEvt_armX(&me->timeEvt, MS_TO_TICK(1), MS_TO_TICK(1));
    #endif
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ValveHandler_Idle_s, // target state
        {
            Q_ACTION_CAST(&ValveHandler_Idle_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ValveHandler::SM::Idle} .............................................
//${AOs::ValveHandler::SM::Idle}
static QState ValveHandler_Idle_e(ValveHandler * const me) {
    Sleep_release(HANDLER_BIT);
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&ValveHandler_Idle_s);
}
//${AOs::ValveHandler::SM::Idle}
static QState ValveHandler_Idle_x(ValveHandler * const me) {
    Sleep_request(HANDLER_BIT);
    (void)me; // unused parameter
    return QM_EXIT(&ValveHandler_Idle_s);
}
//${AOs::ValveHandler::SM::Idle}
static QState ValveHandler_Idle(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle::UNLOCK}
        case UNLOCK_SIG: {
            QF_CRIT_ENTRY();
            if (global_valve_value->total_ticks >= global_config.tick) {
                global_valve_value->total_ticks = global_config.tick;
            } else if (global_valve_value->total_ticks <= 0) {
                global_valve_value->total_ticks = 0;
            }
            last_total_ticks = global_valve_value->total_ticks;
            sFLASH_Init();
            QF_CRIT_EXIT();
            QEvt_ctor(&self_evt, VALVE_UPDATE_SIG);
            QACTIVE_POST(AO_ValveHandler, &self_evt, 0U);
            QTimeEvt_disarm(&me->exitEvt);
            static QMTranActTable const tatbl_ = { // tran-action table
                &ValveHandler_Handle_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::VALVE_DAILY}
        case VALVE_DAILY_SIG: {
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::TIMEOUT}
        case TIMEOUT_SIG: {
            #ifdef USE_MODBUS
            eMBPoll();
            #endif
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::ValveHandler::SM::Idle::Handle} .....................................
//${AOs::ValveHandler::SM::Idle::Handle}
static QState ValveHandler_Handle(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle::Handle::LOCK}
        case LOCK_SIG: {
            QTimeEvt_rearm(&me->exitEvt, MS_TO_TICK(2000));
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_UPDATE}
        case VALVE_UPDATE_SIG: {
            #ifdef DEBUG
            SEGGER_SYSVIEW_MarkStart(VALVE_UPDATE_EVENT);
            #endif
            // QF_CRIT_ENTRY();
            // if (global_valve_value->total_ticks >= global_config.tick) {
            //     global_valve_value->current_status = VALVE_STATUS_ON;
            //     lcd_set_char(LCD_CHAR_OPEN_CHINESE, true);
            //     lcd_set_char(LCD_CHAR_OPEN_ARROW, true);
            //     lcd_set_char(LCD_CHAR_CLOSE_CHINESE, false);
            //     lcd_set_char(LCD_CHAR_CLOSE_ARROW, false);
            // } else if (global_valve_value->total_ticks <= 0) {
            //     global_valve_value->current_status = VALVE_STATUS_OFF;
            //     lcd_set_char(LCD_CHAR_CLOSE_CHINESE, true);
            //     lcd_set_char(LCD_CHAR_CLOSE_ARROW, true);
            //     lcd_set_char(LCD_CHAR_OPEN_CHINESE, false);
            //     lcd_set_char(LCD_CHAR_OPEN_ARROW, false);
            // }
            // QF_CRIT_EXIT();
            QTimeEvt_rearm(&me->persistEvt, MS_TO_TICK(2000));

            if (update_handle != NULL) {
                update_handle(global_valve_value);
            }
            #ifdef DEBUG
            SEGGER_SYSVIEW_MarkStop(VALVE_UPDATE_EVENT);
            #endif
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_CONFIG_WRITE}
        case VALVE_CONFIG_WRITE_SIG: {
            ValveEvt const *ve = (ValveEvt const *)e;
            memcpy(&global_config, ve->msg, sizeof(cmd_config_t));
            QF_CRIT_ENTRY();
            sFLASH_EraseSector(CONF_ADDR_EXFLASH);
            sFLASH_WriteBuffer((uint8_t*)&global_config, CONF_ADDR_EXFLASH, sizeof(cmd_config_t));
            QF_CRIT_EXIT();
            APP_LOG_INFO("Config written to flash");
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_CONFIG_READ}
        case VALVE_CONFIG_READ_SIG: {
            ValveEvt const* ve = (ValveEvt const*)e;
            if (ve->handle != NULL) {
                ve->handle(&global_config);
            }
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_EXIT}
        case VALVE_EXIT_SIG: {
            QF_CRIT_ENTRY();
            APP_LOG_DEBUG("write flash %d", last_total_ticks);
            uint32_t *p = (uint32_t *)&global_valve_store;
            size_t len = sizeof(ValveValStore) / sizeof(uint32_t);
            flash_erase_page(DATA_ADDR_FLASH);
            for (size_t i = 0; i < len; ++i) {
                flash_program_word(DATA_ADDR_FLASH + i * 4, p[i]);
            }
            sFLASH_DeInit();
            use_flash_data = true;
            QF_CRIT_EXIT();
            static QMTranActTable const tatbl_ = { // tran-action table
                &ValveHandler_Idle_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_INFO_READ}
        case VALVE_INFO_READ_SIG: {
            ValveEvt const* ve = (ValveEvt const*)e;
            if (ve->handle != NULL && ve->msg != NULL) {
                int is_enable = (intptr_t)ve->msg;
                if (is_enable) {
                    update_handle = ve->handle;
                    QEvt_ctor(&self_evt, VALVE_UPDATE_SIG);
                    QACTIVE_POST(AO_ValveHandler, &self_evt, 0U);
                }else{
                    update_handle = NULL;
                }
            }
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_TUNING_START}
        case VALVE_TUNING_START_SIG: {
            QF_CRIT_ENTRY();
            global_valve_value->total_ticks = 0;
            lcd_set_char(LCD_CHAR_CLOSE_CHINESE, true);
            lcd_set_char(LCD_CHAR_CLOSE_ARROW, true);
            lcd_set_char(LCD_CHAR_OPEN_CHINESE, false);
            lcd_set_char(LCD_CHAR_OPEN_ARROW, false);
            QF_CRIT_EXIT();
            APP_LOG_DEBUG("calibration Start");
            static QMTranActTable const tatbl_ = { // tran-action table
                &ValveHandler_Tuning_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_PERSIST}
        case VALVE_PERSIST_SIG: {
            if (global_valve_value->total_ticks != last_total_ticks) {
                QF_CRIT_ENTRY();
                uint32_t *p = (uint32_t *)&global_valve_store;
                size_t len = sizeof(ValveValStore) / sizeof(uint32_t);
                flash_erase_page(DATA_ADDR_FLASH);
                for (size_t i = 0; i < len; ++i) {
                    flash_program_word(DATA_ADDR_FLASH + i * 4, p[i]);
                }
                last_total_ticks = global_valve_value->total_ticks;
                use_flash_data = true;
                APP_LOG_DEBUG("write flash %d", last_total_ticks);
                QF_CRIT_EXIT();
            }
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_REFACTORY}
        case VALVE_REFACTORY_SIG: {
            QF_CRIT_ENTRY();
            flash_erase_page(DATA_ADDR_FLASH);
            sFLASH_EraseSector(CONF_ADDR_EXFLASH);
            QF_CRIT_EXIT();
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::VALVE_REBOOT}
        case VALVE_REBOOT_SIG: {
            if (global_valve_value->total_ticks != last_total_ticks) {
                QF_CRIT_ENTRY();
                uint32_t *p = (uint32_t *)&global_valve_store;
                size_t len = sizeof(ValveValStore) / sizeof(uint32_t);
                flash_erase_page(DATA_ADDR_FLASH);
                for (size_t i = 0; i < len; ++i) {
                    flash_program_word(DATA_ADDR_FLASH + i * 4, p[i]);
                }
                last_total_ticks = global_valve_value->total_ticks;
                use_flash_data = true;
                APP_LOG_DEBUG("write flash %d", last_total_ticks);
                QF_CRIT_EXIT();
            }
            NVIC_SystemReset();
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::ValveHandler::SM::Idle::Handle::Tuning} .............................
//${AOs::ValveHandler::SM::Idle::Handle::Tuning}
static QState ValveHandler_Tuning(ValveHandler * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ValveHandler::SM::Idle::Handle::Tuning::VALVE_TUNING_STOP}
        case VALVE_TUNING_STOP_SIG: {
            QF_CRIT_ENTRY();
            global_config.tick = global_valve_value->total_ticks;
            sFLASH_EraseSector(CONF_ADDR_EXFLASH);
            sFLASH_WriteBuffer((uint8_t*)&global_config, CONF_ADDR_EXFLASH, sizeof(cmd_config_t));
            lcd_set_char(LCD_CHAR_OPEN_CHINESE, true);
            lcd_set_char(LCD_CHAR_OPEN_ARROW, true);
            lcd_set_char(LCD_CHAR_CLOSE_CHINESE, false);
            lcd_set_char(LCD_CHAR_CLOSE_ARROW, false);
            QF_CRIT_EXIT();
            QEvt_ctor(&self_evt, VALVE_UPDATE_SIG);
            QACTIVE_POST(AO_ValveHandler, &self_evt, 0U);
            APP_LOG_DEBUG("calibration Done");
            static QMTranActTable const tatbl_ = { // tran-action table
                &ValveHandler_Handle_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${AOs::ValveHandler::SM::Idle::Handle::Tuning::VALVE_UPDATE}
        case VALVE_UPDATE_SIG: {
            if (update_handle != NULL) {
                update_handle(global_valve_value);
            }
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}
//$enddef${AOs::ValveHandler} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
